use mysql;
create database imp;
use imp;
create TABLE DEPT(DEPTNO int primary key,DNAME varchar(50),DLOC varchar(50));
create table EMPLOYEE(EMPNO int primary key,ENAME varchar(50),MGR_NO int,HIREDATA date, SAL decimal(10,1),DEPTNO int, foreign key(DEPTNO) references DEPT(DEPTNO));
create table PROJECT(PNO int primary key,PNAME varchar(50), PLOC varchar(50));
create table INCENTIVES(EMPNO int, INCENTIVE_DATE date primary key,INCENTIVE_AMOUNT int, foreign key(EMPNO) references EMPLOYEE(EMPNO));
create table assigned_to(EMPNO int,PNO int, JOB_ROLE varchar(50),primary key(EMPNO,PNO), foreign key(PNO) references PROJECT(PNO), foreign key(EMPNO) references EMPLOYEE(EMPNO));
insert into DEPT values(10,'HR','BENGALURU');
insert into DEPT values(20,'FINACE','HYDERABAD');
insert into DEPT values(30,'IT','MYSORE');
insert into DEPT values(40,'MARKETING','CHENNAI');
insert into DEPT values(50,'R&D','DELHI');
insert into EMPLOYEE values(1,'NISHANT',null,'2024-10-17',60000.0,30);
insert into EMPLOYEE values(2,'PRATHAM',1,'2024-09-16',50000.0,10);
insert into EMPLOYEE values(3,'PRABHAV',1,'2024-11-16',40000.0,30);
insert into EMPLOYEE values(4,'PRASOON',1,'2023-10-17',30000.0,50);
insert into EMPLOYEE values(5,'PARTH',2,'2024-08-10',300000.0,20);
insert into EMPLOYEE values(6,'PRUTHVI',2,'2024-07-10',300000.0,20);
insert into PROJECT values(1,'A','BENGALURU');
insert into PROJECT values(2,'B','MYSORE');
insert into PROJECT values(3,'C','HYDERABAD');
insert into PROJECT values(4,'D','MYSORE');
insert into PROJECT values(5,'E','BENGALURU');
insert into INCENTIVES values(1,'2025-05-20',40000);
insert into INCENTIVES values(2,'2025-10-01',30000);
insert into INCENTIVES values(3,'2025-10-20',20000);
insert into INCENTIVES values(4,'2025-09-09',10000);
insert into INCENTIVES values(5,'2025-01-20',0);
insert into assigned_to values(1,1,'developer');
insert into assigned_to values(2,2,'HR');
insert into assigned_to values(3,3,'developer');
insert into assigned_to values(4,4,'scientist');
insert into assigned_to values(5,5,'finace manager');
select fe ENAME from EMPLOYEE e where  e.EMPNO in (select MGR_NO from EMPLOYEE group by MGR_NO having e.sal>AVG(sal)); 
